### PR TITLE
Npick fix

### LINKED ISSUE #340: Lwt.npick is broken
It seems that trying to resolve `Lwt.npick`, when the argument promises are initially pending, results in a promise that fails with `Lwt.Canceled`:

```ocaml
open Lwt.Infix

let () =
  let p1, r = Lwt.task () in
  let p2, _ = Lwt.task () in

  let p3 = Lwt.npick [p1; p2] in
  assert (Lwt.state p3 = Lwt.Sleep);

  Lwt.wakeup r ();

  (* Expected: *)
  (* assert (Lwt.state p3 = Lwt.Return [()]) *)

  (* Actual: *)
  assert (Lwt.state p3 = Lwt.Fail Lwt.Canceled);

(* ocamlfind opt -linkpkg -package lwt npick.ml && ./a.out *)
```

By comparison, if you replace `npick` with `nchoose`, you get the Expected behavior.

Since nobody has complained about this, I guess nobody is actually using `npick` with pending promises :)

### PR DESCRIPTION
**Pull request by ZackC**
#340 - removed the line that causes a list of pending promises to be canceled.

### CODE REVIEW

**Comment by ZackC** [comment]
From my understanding the build checks fail because of these tests in ./test/core/test_lwt.ml:   

(* The behavior of [p] tested here is a current bug in [Lwt.npick]. *)
  test "npick: pending, resolves" begin fun () ->
    let p1, _ = Lwt.task () in
    let p2, r = Lwt.task () in
    let p = Lwt.npick [p1; p2] in
    assert (Lwt.state p = Lwt.Sleep);
    Lwt.wakeup r "foo";
    Lwt.return
      (Lwt.state p1 = Lwt.Fail Lwt.Canceled &&
       Lwt.state p = Lwt.Fail Lwt.Canceled)
  end;

  (* This is the same bug as above. *)
  test "npick: pending, fails" begin fun () ->
    let p1, _ = Lwt.task () in
    let p2, r = Lwt.task () in
    let p = Lwt.npick [p1; p2] in
    Lwt.wakeup_exn r Exception;
    Lwt.return
      (Lwt.state p1 = Lwt.Fail Lwt.Canceled &&
       Lwt.state p = Lwt.Fail Lwt.Canceled)
  end;

**Comment by ZackC** [comment]
New commit that moves the cancellation of promises to after some of them have the chance to complete.

**Comment by ZackC** [comment]
Huh, the build produced an unable to install parsetree error.  That shouldn't be related to the changes I made.

**Comment by aantron** [comment]
Indeed it's not, see https://github.com/let-def/ocaml-migrate-parsetree/issues/19#issuecomment-317189028. We can just ignore that build row for now; I'll list in `allowed_failures:` later.

File: src/core/lwt.ml [hunk 1]
```diff
@@ -2534,9 +2534,9 @@ struct
         let callback in_completion_loop _result =
           let State_may_now_be_pending_proxy p = may_now_be_proxy p in
           let p = underlying p in
-          List.iter cancel ps;
           let State_may_have_changed p =
             finish_nchoose_or_npick_after_pending in_completion_loop p [] ps in
+          List.iter cancel ps;
```
Comment (aantron) [inline src/core/lwt.ml]: I believe this reordering produces the correct behavior.

There is one weird thing about Lwt now, though:

- The [callback of `Lwt.pick`](https://github.com/ocsigen/lwt/blob/424e4c50ef84d359bf0389e9fdb37ef66cbd1c3f/src/core/lwt.ml#L2398-L2404) cancels the pending promises *before* completing its own ("final") promise.
- This modified callback of `Lwt.npick` cancels the pending promises *after* completing its own promise.

This means that code running in `on_cancel` and regular callbacks of the respective pending promises can observe different states of the final promise depending on which function is used. Likewise, code running in the callbacks of the final promises can observe different states of the (to-be) canceled promises, depending on which function is used.

I'm not sure if that's really a problem, since we don't document or guarantee either behavior, and I'm not aware of any pathological interactions due to picking one or the other, so one could argue that this doesn't need to be addressed right now.

However, it could cause problems for users refactoring their code. For completeness, this could be addressed by factoring out the [implicit final promise completion](https://github.com/ocsigen/lwt/blob/424e4c50ef84d359bf0389e9fdb37ef66cbd1c3f/src/core/lwt.ml#L2433) from `finish_nchoose_or_npick_after_pending`, so that function only collects the result, and the [callback](https://github.com/ocsigen/lwt/blob/424e4c50ef84d359bf0389e9fdb37ef66cbd1c3f/src/core/lwt.ml#L2534-L2541) can fully control the order of (1) figuring out the result (2) canceling the pending promises (3) setting the state of the final promise (the one returned by `npick` itself). Callbacks in both `npick` and `nchoose` will have to be modified to call `complete` explicitly.

File: test/core/test_lwt.ml [hunk 2]
```diff
@@ -2361,7 +2374,7 @@ let npick_tests = [
        Lwt.state p = Lwt.Fail Lwt.Canceled)
   end;
 
-  (* This is the same bug as above. *)
```
Comment (aantron) [inline test/core/test_lwt.ml]: This is fine, but FYI OCaml supports nested comments, so this can be reverted.

File: test/core/test_lwt.ml [hunk 3]
```diff
@@ -2349,7 +2349,20 @@ let npick_tests = [
...
+  test "npick: all pending" begin fun () ->
+    let p1, r = Lwt.task () in
+    let p2, _ = Lwt.task () in
+    let p3 = Lwt.npick [p1; p2] in
+    Lwt.wakeup r ();
+    (* Expected: *)
+    Lwt.return (Lwt.state p3 = Lwt.Return [()])
+    (* Actual: *)
+    (*Lwt.return (Lwt.state p3 = Lwt.Fail Lwt.Canceled)*)
+  end;
```
Comment (aantron) [inline test/core/test_lwt.ml]: Thanks for inserting this here!

File: src/core/lwt.ml (hunk 1 above)
Comment (aantron) [inline src/core/lwt.ml]: A secondary reason to prefer the ordering in `pick` is that function gets used a lot, so presumably that behavior is not problematic.

**Comment by aantron** [comment]
@ZackC I wrote a small program to show the two behaviors, in part for my own education, but it may also be helpful for ensuring same ordering: https://gist.github.com/aantron/4db12b8e5ca92f57f7a223e594c833cc

**Comment by aantron** [comment]
Thanks for fixing this!

**Comment by ZackC** [comment]
No problem. Glad to help!
